final Map<String,String> frLangData = {
  'hw': 'Hello,',

  'devise': 'Fr cfa',
  'connectToApp': 'Connectez vous à \nTout Chariot',
  'numTel': 'Numéro de téléphone',
  'password': 'Mot de passe',
  'forgetPwd': 'Mot de passe oublié ?',
  'recoverAccount': 'Récupérer le compte',
  'alreadyRegistered': 'Vous êtes déjà inscrit ?',
  'registerYou': 'Inscrivez vous',
  'login': 'Se connecter',

  'registeredToApp': "S'inscrire sur Tout Chariot",
  'last_name': 'Nom',
  'first_name': 'Prénom',
  'email': 'E-mail',
  'confirmPwd': 'Confirmer le mot de passe',
  'acceptTerm': 'En vous inscrivant vous accepter ?',
  'termOfUse': "condition d'utilisation",
  'andOur': "et nos",
  'privacyPolicy': 'politique de confidentialité',
  'notHaveAccount': "Vous n'avez pas de compte ?",
  'loginYou': 'Connectez vous',
  'register': "S'inscrire",

  'race': 'Courses',
  'home': 'Accueil',
  'myAccount': 'Mon compte',

  'app': 'Tout Chariot',
  'welcome': 'Bienvenue',
  'yourWallet': 'Votre portefeuille',
  'topUp': 'Recharger',
  'searchCart': 'Recherche de chariot',
  'someMachine': 'Quelques engins',
  'grue': 'Grue',
  'recentRaces': 'Récentes courses',

  'onWatting': 'En attente',
  'inProgress': 'En cours',
  'accomplish': 'Accomplie',
  'travel': 'voyage',

  'lunchRequest': 'Lancer la demande',
  'estimatePrice': "Estimation du prix",
  'carType': 'Type de vehicule',

  'defineTravel': 'Définissez le trajet',
  'chooseStartAddress': "Choisir l'adresse de départ",
  'chooseEndAddress': "Choisir l'adresse de destination",
};