Map<String, String> frLanguage = {
  'app': 'Tout Chariot',
  'devise': 'Fr cfa',
  'connectToApp': 'Connectez vous à \nTout Chariot',
  'registeredToApp': "S'inscrire sur Tout Chariot",
  'numTel': 'Numéro de téléphone',
  'password': 'Mot de passe',
  'forgetPwd': 'Mot de passe oublié ?',
  'recoverAccount': 'Récupérer le compte',
  'login': 'Se connecter',
  'loginYou': 'Connectez vous',
  'alreadyRegistered': 'Vous êtes déjà inscrit ?',
  'register': "S'inscrire",
  'registerYou': 'Inscrivez vous',
  'name': 'Nom',
  'prenom': 'Prénom',
  'confirmPwd': 'Confirmer le mot de passe',
  'acceptTerme': 'En vous inscrivant vous accepter ?',
  'termeOfUse': "condition d'utilisation",
  'andOur': "et nos",
  'privacyPolicy': 'politique de confidentialité',
  'notHaveAccount': "Vous n'avez pas de compte ?",
  'welcome': 'Bienvenue',
  'yourWallet': 'Votre portefueille',
  'topUp': 'Recharger',
  'searchCart': 'Recherche de chariot',
  'someMachine': 'Quelques engins',
  'grue': 'Grue',
  'tricycle': 'Tricycle',
  'truck': 'Camion',
  'recentRaces': 'Récentes courses',
  'order': 'Commande',
  'de': 'De',
  'to': 'À',
  'cargo': 'Cargaison',
  'race': 'Courses',
  'home': 'Accueil',
  'myAccount': 'Mon compte',
  'kilometre': 'Kilomètre',
  'cart': 'Chariot',
  'travel': 'voyage',
  'onWatting': 'En attente',
  'inProgress': 'En cours',
  'accomplish': 'Accomplie',
  'defineTravel': 'Définissez le trajet',
  'chooseStartAddress': "Choisir l'adresse de départ",
  'chooseEndAddress': "Choisir l'adresse de destination",
  'estimatePrice': "Estimation du prix",
  'carType': 'Type de vehicule',
  'lunchRequest': 'Lancer la demande',
  'chooseAddressOf': "Choisir l'adresse de ...",
  'startAddress': 'Adresse de départ',
  'departure': 'Départ',
  'destination': 'Destination',
  'valideStartAddress': "Valider l'adresse de départ",
  'cargoDetail': 'Détails de la cargaison',
  'watingDriver': 'En Attente De Navigateur',
  'userWatingMsg': 'Vous allez patienter un tout petit instant un navigateur prendra en charge votre course',
  'inWating': 'En attente'
};
